language: node_js
node_js:
  - node
addons:
  chrome: stable
deploy:
  provider: heroku
  api_key:
    secure: Y7JbC+58snrVssNOh8+unPvAhnT+V1npBCx1Gohzs2H4zKW51jbPb4sVmB57KGm+b9E9IzX/o5Ojm7hnsRYc8INPzhgkj+SH6pFyE6KJAmxbPDdNQ9aHKYNR0DyzcNAn67ox1SwmPCYG/NP/Da4NgyYX9C3mOqPpBREpwLtq2v1KQ7x8/Cxu6ajIW79jyFTrJiqnhtzFJcQcUFMsYBhgiuWTKo67MF0aJmWKi+C0Nu5CYEf1PBz+KvbA339hOzvlmwaOoxMeUPkYznJ/plQw9WpsUctnCQPyUAhv9b5jKn016daqyQMGuWTcA/GVxJT+qndHzVMsiMM+eV0N1+F01GbALN/xNzy7yvYkaeoAKmI9UOJAGfJv90c7CsfurzuY5w6afhKXoEhvs2MqgHOynHP7nHxJu1ukhwK7CmY7PL3huthbBXMPFJqxxf3kjBXo16uA5w9Esu+K4z/DnhmTEV/LyV6sYQJpmzp/qijfMYKN8TV941vypVMu8sW0D1kNMKJAVdD9QQZnnE1DXvlD9FSZ1SlONm9ezRls8Qy3KJIRZlEcOHDJAxvdAZUaPXPrUGrA5Ni/8BvjdYwJdxpieJ/ojEQLoK2NkzLTKTo1Pl21/t+ioE1QEV3Le25ROAsbnL6WcuffcoLJL7oHzPPl5MsNhlOFUkmqHXsPtHiNQ4I=
  app: fitrition
script:
  - npm run all-tests
  - npm run build
